version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6379"

  backend:
    build: ./service
    container_name: EC-SERVICE
    command: sh entrypoint.sh
    volumes:
      - ./service:/app
    ports:
      - "8000:8000"
    env_file:
      - ./service/.env
    depends_on:
      - redis

  frontend:
    build: ./ui
    container_name: EC-UI
    ports:
      - "3000:80"
    depends_on:
      - backend
