version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6379"

  backend:
    build: ./service
    container_name: EC-SERVICE
    command: sh /app/entrypoint.sh
    volumes:
      - ./service:/app
    ports:
      - "8000:8000"
    env_file:
      - ./service/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./ui
    container_name: EC-UI
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
